#!/bin/bash
#===============================================================================
#
#         FILE:  main
#
#  DESCRIPTION:  Main script for the tool
#
#       AUTHOR:  jvzantvoort (John van Zantvoort), john@vanzantvoort.org
#      CREATED:  2023-01-15
#
#===============================================================================
# Variables: switchable {{{
declare DEBUG="no"
# }}}

# Constants: base {{{
C_SCRIPTPATH="$(readlink -f "$0")"
C_SCRIPTDIR="$(dirname "${C_SCRIPTPATH}")"
C_BUILDNAME="bootstrap_homedir"
readonly C_SCRIPTPATH
readonly C_SCRIPTDIR
readonly C_BUILDNAME
# }}}

if [[ ! -r "${C_SCRIPTDIR}/functions.sh" ]]
then
  printf "Cannot access shared functions\n\n"
  exit 1
fi
source "${C_SCRIPTDIR}/functions.sh"

function list_files()
{
  find "${C_SCRIPTDIR}" -maxdepth 1 -mindepth 1 -type f -name '*.sh' \
    -not -name 'functions.sh' | sort
}

function get_descr()
{
  awk -F':' '/Description/ { print $2 }' "${1}" |sed 's/^\ *//'
}

function __is_digit()
{
  local indx="$1"
  re='^[0-9]+$'
  [[ "$indx" =~ $re ]] && return 0
  return 1
}

function main()
{
  clear
  logos

  menu_items=($(list_files))
  menu_item_no=${#menu_items[@]}

  for (( i=0; i<${menu_item_no}; i++ ));
  do
    item="${menu_items[$i]}"
    name="$(basename "${item}" .sh)"
    descr="$(get_descr "${item}")"
    printf "%2d) %-24s %s\n" "$((i+1))" "${name}" "${descr}"
  done

  printf "\n\n q) quit\n"

  printf "\n  answer: "

  read -n 1 answer

  printf "\n"

  if __is_digit "${answer}"
  then
    answer="${menu_items[$((answer-1))]}"
  fi

  case "${answer}" in
    q) exit;;
  esac

  if [[ -x "${answer}" ]]
  then
    "${answer}"
  fi

  main
}

#------------------------------------------------------------------------------#
#                                    Main                                      #
#------------------------------------------------------------------------------#

main

#------------------------------------------------------------------------------#
#                                  The End                                     #
#------------------------------------------------------------------------------#

# vim: foldmethod=marker
